### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by stefanahman** [newrelic/newrelic_api#11]
It this gem still maintained? Or will you update to support v2?

**Comment by ianfixes** [comment]
I've created a [Swagger 2.0 spec for the v2 API](https://gist.github.com/ianfixes/b5f345384ce58dee5e13535fd48271a2) that you can use to generate your own client in Ruby (or any language).

See [New Relic forum discussion here](https://discuss.newrelic.com/t/api-declaration-swagger-for-example/35365/22?u=ikatz)
